// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEjvHToT63t4FX-t8jdNW_t1YdOFsD54',
    appId: '1:1027814209271:android:0acb994f475c01df4845f2',
    messagingSenderId: '1027814209271',
    projectId: 'cosmic-numeriics-b51e5',
    storageBucket: 'cosmic-numeriics-b51e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJFhDa03aFN-7JLXGI3avrC-1XXIzkK4',
    appId: '1:1027814209271:ios:424bc4dcd64c15884845f2',
    messagingSenderId: '1027814209271',
    projectId: 'cosmic-numeriics-b51e5',
    storageBucket: 'cosmic-numeriics-b51e5.firebasestorage.app',
    iosBundleId: 'com.example.cosmicNumeriics',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYVWjKDHZN0fapPfP-7Ij_RS9T1FbufE',
    appId: '1:1027814209271:web:da7378cceaf6c1de4845f2',
    messagingSenderId: '1027814209271',
    projectId: 'cosmic-numeriics-b51e5',
    authDomain: 'cosmic-numeriics-b51e5.firebaseapp.com',
    storageBucket: 'cosmic-numeriics-b51e5.firebasestorage.app',
    measurementId: 'G-R6JKHXGPL9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJFhDa03aFN-7JLXGI3avrC-1XXIzkK4',
    appId: '1:1027814209271:ios:424bc4dcd64c15884845f2',
    messagingSenderId: '1027814209271',
    projectId: 'cosmic-numeriics-b51e5',
    storageBucket: 'cosmic-numeriics-b51e5.firebasestorage.app',
    iosBundleId: 'com.example.cosmicNumeriics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJYVWjKDHZN0fapPfP-7Ij_RS9T1FbufE',
    appId: '1:1027814209271:web:daa3daf5be18e62c4845f2',
    messagingSenderId: '1027814209271',
    projectId: 'cosmic-numeriics-b51e5',
    authDomain: 'cosmic-numeriics-b51e5.firebaseapp.com',
    storageBucket: 'cosmic-numeriics-b51e5.firebasestorage.app',
    measurementId: 'G-D1GTSG2Q88',
  );

}